public class Constants {
  public static final string PAYMENT_SETTING = 'Payment_Setting';
  public static final string HTTP_POST_METHOD = 'POST';
  public static final string HTTP_GET_METHOD = 'GET';
  public static final string HTTP_DELETE_METHOD = 'DELETE';
  public static final string HTTP_AUTH = 'Authorization';
  public static final string HTTP_BASIC = 'Basic ';
  public static final string HTTP_BEARER = 'bearer ';
  public static final string HTTP_CONTENT_TYPE = 'Content-Type';
  public static final string HTTP_APPLICATION_JSON = 'application/json';
  public static final string HTTP_APPLICATION_XML = 'application/xml';
  public static final string HTTP_CONTENT_ENCODING = 'Content-Encoding';
  public static final string HTTP_HOST = 'Host';
  public static final string HTTP_CONNECTION = 'Connection';
  public static final string HTTP_ACL = 'ACL';
  public static final string HTTP_APPLICATION_CHARSET = 'application/json;charset=UTF-8';
  public static final string STATUS_CODE_SUCCESS = 'S';
  public static final string STATUS_CODE_FAIL = 'F';
}