public with sharing class FormSetting {
  public String id;
  public String formName;
  public String objectReference;
  public String brandColor;
  public String thankYouPageContent;
  public Boolean isUseThankYouPage;
  public Boolean isShowDisclaimer;
  public Boolean isMaxQEqualto1;
  public String duplicateSelected;
  public String priceBookId;
  public String currencyCode;
  public List<Form_Product__c> productList;
  public List<String> productListDel;
}